
services:
  db:
    image: postgres:latest
    container_name: movie-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_scripts:/docker-entrypoint-initdb.d/
    networks:
      - app-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis-movie:
    image: redis:7-alpine
    container_name: movie-of-day
    command: [
      "redis-server",
      "--requirepass", "${REDIS_MOVIE_PASSWORD}",
      "--bind", "0.0.0.0",
      "--protected-mode", "yes"
    ]
    networks:
      - app-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_MOVIE_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-bullmq:
    image: redis:7-alpine
    container_name: redis-bullmq
    command: [
      "redis-server",
      "--requirepass", "${REDIS_BULLMQ_PASSWORD}",
      "--bind", "0.0.0.0",
      "--port", "6380",         
      "--protected-mode", "yes"
    ]
    networks:
      - app-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_BULLMQ_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  api:
    image: kennycheng35/review-guesser-api:v1.0.0
    expose:
      - "${BACKEND_PORT:-3000}" 
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis-movie:
        condition: service_healthy
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${BACKEND_PORT:-3000} 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db    
      - REDIS_MOVIE_HOST=redis-movie
      - REDIS_MOVIE_PORT=6379
      - REDIS_MOVIE_PASSWORD=${REDIS_MOVIE_PASSWORD}
    networks:
      - app-net
    deploy: 
      replicas: 4

  backend-scheduler:
    image: kennycheng35/review-guesser-jobs:v1.0.0
    command: ["node", "jobs/cron/scheduler.js"]
    container_name: backend-scheduler
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis-movie:
        condition: service_healthy
      redis-bullmq:
        condition: service_healthy
    networks:
      - app-net
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db    
      - REDIS_MOVIE_HOST=redis-movie
      - REDIS_MOVIE_PORT=6379
      - REDIS_MOVIE_PASSWORD=${REDIS_MOVIE_PASSWORD}
      - REDIS_BULLMQ_HOST=redis-bullmq
      - REDIS_BULLMQ_PORT=6380
      - REDIS_BULLMQ_PASSWORD=${REDIS_BULLMQ_PASSWORD}

  backend-worker:
    image: kennycheng35/review-guesser-jobs:v1.0.0
    command: ["node", "jobs/cron/worker.js"]
    container_name: backend-worker
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis-movie:
        condition: service_healthy
      redis-bullmq:
        condition: service_healthy
    networks:
      - app-net
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db    
      - REDIS_MOVIE_HOST=redis-movie
      - REDIS_MOVIE_PORT=6379
      - REDIS_MOVIE_PASSWORD=${REDIS_MOVIE_PASSWORD}
      - REDIS_BULLMQ_HOST=redis-bullmq
      - REDIS_BULLMQ_PORT=6380
      - REDIS_BULLMQ_PASSWORD=${REDIS_BULLMQ_PASSWORD}

  frontend:
    image: kennycheng35/review-guesser:v1.0.0
    container_name: review-guesser-frontend
    restart: unless-stopped
    networks:
      - app-net 
    expose:
      - "80"
    environment:
      - NGINX_IPV6_DISABLE=1
  
  reverse-proxy:
    image: nginx:stable-alpine
    container_name: guesser-reverse-proxy-local
    restart: unless-stopped
    ports: ["80:80", "443:443"]
    volumes:
      - ./nginx-proxy/nginx-proxy.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - letsencrypt_certs:/etc/letsencrypt
      - letsencrypt_webroot:/var/www/certbot
      - /opt/certbot-data/conf:/etc/nginx/ssl-options:ro
    networks:
      - app-net
    depends_on: 
      - api
      - frontend
  
  certbot:
    image: certbot/certbot
    container_name: prod-certbot
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - letsencrypt_webroot:/var/www/certbot

networks:
  app-net:
    driver: bridge
  
volumes:
  pgdata:
  letsencrypt_certs:
  letsencrypt_webroot: